### ISSUE TITLE
Request: login functionality

### ISSUE THREAD

**Issue by 0000vt** [reyemb/AISExplorer#1]
Could you add a login function, so we can use more function of marinetraffic? 

From what I found, the following payload is needed to POST to https://www.marinetraffic.com/en/users/ajax_login.

payload = {
    'action': 'login',
    'email': 'emailaddress',
    'password': 'password',
    'is_ajax': 'true'
}
A cookie is then generated and saved in the session for further use.

**Comment by reyemb** [comment]
I will have a look adding this functionality, can you tell me more about the functions you plan to use? 

Do you want to use premium functions?

**Comment by 0000vt** [comment]
Yeah for example premium functions or managing personal fleets. However, im not sure if it's safe to send the credentials through the proxies though.

**Comment by reyemb** [comment]
If you are logged in than there is no need for you to use proxies because you aren`t anonymous anymore.

So I can make sure that when you use the login function that proxies will be disabled.

I will check if I can add function for getting personal fleets and the premium columns like voyage data, etc.. Are you looking for those premium functions?

**Comment by 0000vt** [comment]
Yeah I already got the vessel_positions asset working in my own code. Cloudfare is limiting my requests though, so proxies would be the only reason to get bypass the cloudfare errors. 
In premium you've got the following asset_types:
'vessel_positions', 'vessel_positions_and_weather', 'voyage_timeline', 'vessel_events', 'arrivals_departures', 'berth_calls'. Could be a nice thing to add to your project.

**Comment by reyemb** [comment]
How many data records are you fetching in total?

 I will have a look at it this weekend!

**Comment by 0000vt** [comment]
That depends on the request. Sometime around 10k rows for a location history of a ship. I've scripted it to split it into chunks of 400-500 rows per request if the total request has more than 500 rows. I used a timeout of 30 seconds between the requests to keep cloudfare at bay, but sometimes it still kicks me out.

**Comment by reyemb** [comment]
I have taken a look at it. 

I am unsure if it is a good idea to use proxys with credentials. Some ressource say if you are using https proxies (which is the default) then you should be save and mitm attacks shouldn't be possible. Other ressources say that it is kind of risky. Don't know for sure.

I have managed to add a loggin function, a function for getting fleets created by a user and receiving data for custom fleets. Now I am trying to implement the premium columns. Which plan are you using currently? Is the standard one enough or do I need the professionel one?

I will make an upgrade of the package this week.

**Comment by reyemb** [comment]
Added login functionalities and functions for fetching custom fleets. If premium columns are needed. Please open new Issue
